language: node_js

env:
  global:
    - NODE_OPTIONS="--openssl-legacy-provider"

node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: dist
 on:
   branch: main
   